package ccpm.core;

import java.awt.Color;
import java.util.Arrays;

import DummyCore.Blocks.BlocksRegistry;
import DummyCore.Core.Core;
import DummyCore.Items.ItemRegistry;
import DummyCore.Utils.MiscUtils;
import DummyCore.Utils.ModVersionChecker;
import ccpm.biomes.Wasteland;
import ccpm.blocks.BlockEnergyCellBase;
import ccpm.commands.CommandGetPollution;
import ccpm.commands.CommandGetRegTiles;
import ccpm.commands.CommandIncPollution;
import ccpm.commands.CommandTestWand;
import ccpm.handlers.ChunkHandler;
import ccpm.handlers.PlayerHandler;
import ccpm.handlers.WorldHandler;
import ccpm.items.RespiratorBase;
import ccpm.network.proxy.CommonProxy;
import ccpm.potions.PotionSmog;
import ccpm.render.CCPMRenderHandler;
import ccpm.render.RenderRespirator;
import ccpm.tiles.TileEnergyCellMana;
import ccpm.tiles.TileEnergyCellRf;
import ccpm.tiles.TileEnergyCellThaumium;
import ccpm.utils.config.CCPMConfig;
import ccpm.utils.config.PollutionConfig;
import cpw.mods.fml.common.FMLCommonHandler;
import cpw.mods.fml.common.FMLLog;
import cpw.mods.fml.common.Loader;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.Mod.Instance;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPostInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.event.FMLServerStartingEvent;
import cpw.mods.fml.common.registry.GameRegistry;
import net.minecraft.block.Block;
import net.minecraft.block.material.Material;
import net.minecraft.command.CommandHandler;
import net.minecraft.item.Item;
import net.minecraft.server.MinecraftServer;
import net.minecraft.village.MerchantRecipe;
import net.minecraft.village.MerchantRecipeList;
import net.minecraftforge.common.BiomeManager;
import net.minecraftforge.common.BiomeManager.BiomeEntry;
import net.minecraftforge.common.BiomeManager.BiomeType;
import net.minecraftforge.common.MinecraftForge;

@Mod(modid = CCPM.MODID, name = CCPM.NAME, version = CCPM.version, dependencies = CCPM.dependencies)
public class CCPM {

	public static final String MODID = "ccpm";
	public static final String NAME = /*"Artem226's Climate Change And Pollution Mod"*/ "Artem226's Ecology Mod";
	public static final String version = "0.1.1710.0";
	public static final String dependencies = "required-after:DummyCore;";
	
	public static Item respirator = new RespiratorBase("ccpmRespirator", RespiratorBase.respiratorMatter);
	
	Block cell = new BlockEnergyCellBase();
	
	
	@Instance(MODID)
	public static CCPM instance;
	
	public static CCPMConfig cfg = new CCPMConfig();
	
	@SidedProxy(clientSide = "ccpm.network.proxy.ClientProxy", serverSide = "ccpm.network.proxy.CommonProxy")
	public static CommonProxy proxy;
	
	public static PotionSmog smog;
	
	public static Wasteland wasteland;
	
	/*
	 * URL to my GitHub 
	 */
	public static final String githubURL = "https://github.com/Artem226";
	
	@EventHandler
	public void preLoad(FMLPreInitializationEvent event)
	{
		instance = this;
		Core.registerModAbsolute(getClass(), NAME, event.getModConfigurationDirectory().getAbsolutePath(), cfg);
		
		PollutionConfig.load(event.getModConfigurationDirectory().getAbsolutePath());
		
		ModVersionChecker.addRequest(getClass(), "https://raw.githubusercontent.com/Artem226/MinecraftEcologyMod/master/version.txt");
		
		
		ModMetadata meta = event.getModMetadata();
		meta.authorList = Arrays.asList(new String[]{"Artem226"});
		meta.autogenerated = false;
		meta.description = "Mod, that adds pollution and climate changing system in the Minecraft";
		meta.version = version;
		meta.modId = MODID;
		meta.name = NAME;
		meta.credits = "Author: Artem226";
		
		
		smog = new PotionSmog(MiscUtils.extendPotionArray(1), false, new Color(61, 54 , 54).getRGB());

		wasteland = new Wasteland(CCPMConfig.wasteId);
		
		BiomeManager.addBiome(BiomeType.WARM, new BiomeEntry(wasteland, 14));
	}
	
	@EventHandler
	public void load(FMLInitializationEvent event)
	{
		if(instance != this)
			instance = this;
		FMLLog.info("[CCPM]Initialising");
		MinecraftForge.EVENT_BUS.register(new WorldHandler());
		//FMLCommonHandler.instance().bus().register(new WorldHandler());
		MinecraftForge.EVENT_BUS.register(new ChunkHandler());
		//FMLCommonHandler.instance().bus().register(new ChunkHandler());
		MinecraftForge.EVENT_BUS.register(new PlayerHandler());
		//FMLCommonHandler.instance().bus().register(new PlayerHandler());
		
		ItemRegistry.registerItem(respirator, "itemRespirator", getClass());
		
		BlocksRegistry.registerBlock(cell, "ccpm.energycell", getClass(), null);
		
		GameRegistry.registerTileEntity(TileEnergyCellMana.class, "TECM");
		GameRegistry.registerTileEntity(TileEnergyCellRf.class, "TECR");
		GameRegistry.registerTileEntity(TileEnergyCellThaumium.class, "TECT");
	    
		MinecraftForge.EVENT_BUS.register(new CCPMRenderHandler());
		
		//FMLCommonHandler.instance().
		if(proxy!=null)
		{
			//proxy.registerItemRenders();
			//proxy.registerRenderHandler();
		}
	}
	
	@EventHandler
	public void postLoad(FMLPostInitializationEvent event)
	{
		if(instance != this)
			instance = this;
	}
	
	@EventHandler
	public void serverStart(FMLServerStartingEvent event)
	{
		event.registerServerCommand(new CommandGetPollution());
		event.registerServerCommand(new CommandTestWand());
		//event.registerServerCommand(new CommandGetRegTiles());
		event.registerServerCommand(new CommandIncPollution());
	}

	//Function to tell you where you have to report errors
	public static void addToEx()
	{
		FMLLog.warning("[CCPM]Please, report this to the author's(Artem226) GitHub!!!");
		FMLLog.bigWarning(githubURL);
		FMLLog.info("[CCPM]Please, don't forget to include crash report/log");
	}
}
