// Date: 24.01.2016 10:41:27
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package ccpm.render.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelBiped;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelRespirator extends ModelBase
{
  //fields
	/*
    ModelRenderer head;
    ModelRenderer body;
    ModelRenderer rightarm;
    ModelRenderer leftarm;
    ModelRenderer rightleg;
    ModelRenderer leftleg;
    */
    ModelRenderer Shape1;
    ModelRenderer Shape11;
    ModelRenderer Shape12;
    ModelRenderer Shape13;
    ModelRenderer Shape14;
    ModelRenderer Tube;
    ModelRenderer Shape1r;
    ModelRenderer Filter1;
    ModelRenderer Filter2;
  
  public ModelRespirator()
  {
	  
    textureWidth = 128;
    textureHeight = 64;
    
    
    /*
      head = new ModelRenderer(this, 0, 0);
      head.addBox(-4F, -8F, -4F, 8, 8, 8);
      head.setRotationPoint(0F, 0F, 0F);
      head.setTextureSize(128, 64);
      head.mirror = true;
      setRotation(head, 0F, 0F, 0F);
      body = new ModelRenderer(this, 16, 16);
      body.addBox(-4F, 0F, -2F, 8, 12, 4);
      body.setRotationPoint(0F, 0F, 0F);
      body.setTextureSize(128, 64);
      body.mirror = true;
      setRotation(body, 0F, 0F, 0F);
      rightarm = new ModelRenderer(this, 40, 16);
      rightarm.addBox(-3F, -2F, -2F, 4, 12, 4);
      rightarm.setRotationPoint(-5F, 2F, 0F);
      rightarm.setTextureSize(128, 64);
      rightarm.mirror = true;
      setRotation(rightarm, 0F, 0F, 0F);
      leftarm = new ModelRenderer(this, 40, 16);
      leftarm.addBox(-1F, -2F, -2F, 4, 12, 4);
      leftarm.setRotationPoint(5F, 2F, 0F);
      leftarm.setTextureSize(128, 64);
      leftarm.mirror = true;
      setRotation(leftarm, 0F, 0F, 0F);
      rightleg = new ModelRenderer(this, 0, 16);
      rightleg.addBox(-2F, 0F, -2F, 4, 12, 4);
      rightleg.setRotationPoint(-2F, 12F, 0F);
      rightleg.setTextureSize(128, 64);
      rightleg.mirror = true;
      setRotation(rightleg, 0F, 0F, 0F);
      leftleg = new ModelRenderer(this, 0, 16);
      leftleg.addBox(-2F, 0F, -2F, 4, 12, 4);
      leftleg.setRotationPoint(2F, 12F, 0F);
      leftleg.setTextureSize(128, 64);
      leftleg.mirror = true;
      setRotation(leftleg, 0F, 0F, 0F);
      */
      Shape1 = new ModelRenderer(this, 60, 0);
      Shape1.addBox(0F, 0F, 0F, 8, 1, 1);
      Shape1.setRotationPoint(-4F, -8F, -5F);
      Shape1.setTextureSize(128, 64);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
      Shape11 = new ModelRenderer(this, 36, 0);
      Shape11.addBox(0F, 0F, 0F, 8, 1, 1);
      Shape11.setRotationPoint(-4F, -7F, -6F);
      Shape11.setTextureSize(128, 64);
      Shape11.mirror = true;
      setRotation(Shape11, 0F, 0F, 0F);
      Shape12 = new ModelRenderer(this, 36, 12);
      Shape12.addBox(0F, 0F, 0F, 8, 1, 2);
      Shape12.setRotationPoint(-3F, -8F, -6F);
      Shape12.setTextureSize(128, 64);
      Shape12.mirror = true;
      setRotation(Shape12, 0F, 0F, 1.570796F);
      Shape13 = new ModelRenderer(this, 36, 7);
      Shape13.addBox(0F, 0F, 0F, 8, 1, 2);
      Shape13.setRotationPoint(-4F, -1F, -6F);
      Shape13.setTextureSize(128, 64);
      Shape13.mirror = true;
      setRotation(Shape13, 0F, 0F, 0F);
      Shape14 = new ModelRenderer(this, 36, 3);
      Shape14.addBox(0F, 0F, 0F, 8, 1, 2);
      Shape14.setRotationPoint(3F, 0F, -6F);
      Shape14.setTextureSize(128, 64);
      Shape14.mirror = true;
      setRotation(Shape14, 0F, 0F, -1.570796F);
      Tube = new ModelRenderer(this, 0, 34);
      Tube.addBox(0F, 0F, 0F, 2, 2, 6);
      Tube.setRotationPoint(-1F, -1F, -10F);
      Tube.setTextureSize(128, 64);
      Tube.mirror = true;
      setRotation(Tube, 0.3346075F, 0F, 0F);
      Shape1r = new ModelRenderer(this, 60, 14);
      Shape1r.addBox(0F, 0F, 0F, 8, 2, 4);
      Shape1r.setRotationPoint(-4F, 0F, -7F);
      Shape1r.setTextureSize(128, 64);
      Shape1r.mirror = true;
      setRotation(Shape1r, 1.570796F, 0F, 0F);
      Filter1 = new ModelRenderer(this, 20, 34);
      Filter1.addBox(0F, 0F, 0F, 3, 1, 3);
      Filter1.setRotationPoint(2F, -2F, -10F);
      Filter1.setTextureSize(128, 64);
      Filter1.mirror = true;
      setRotation(Filter1, 0F, 0F, 1.570796F);
      Filter2 = new ModelRenderer(this, 20, 34);
      Filter2.addBox(0F, 0F, 0F, 3, 1, 3);
      Filter2.setRotationPoint(-1F, -2F, -10F);
      Filter2.setTextureSize(128, 64);
      Filter2.mirror = true;
      setRotation(Filter2, 0F, 0F, 1.570796F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5,entity);
    /*
    head.render(f5);
    body.render(f5);
    rightarm.render(f5);
    leftarm.render(f5);
    rightleg.render(f5);
    leftleg.render(f5);
    */
    Shape1.render(f5);
    Shape11.render(f5);
    Shape12.render(f5);
    Shape13.render(f5);
    Shape14.render(f5);
    Tube.render(f5);
    Shape1r.render(f5);
    Filter1.render(f5);
    Filter2.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  

}
