package ecomod.core;

import ecomod.core.*;
import ecomod.core.stuff.EMBlocks;
import ecomod.core.stuff.EMConfig;
import ecomod.core.stuff.MainRegistry;
import net.minecraft.util.ResourceLocation;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.common.config.Configuration;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.*;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.SidedProxy;
import net.minecraftforge.fml.common.event.*;
import net.minecraftforge.fml.common.event.FMLInterModComms.IMCEvent;
import net.minecraftforge.fml.common.event.FMLInterModComms.IMCMessage;
import net.minecraftforge.fml.common.registry.GameData;
import ecomod.common.pollution.TEPollutionConfig;
import ecomod.common.pollution.TEPollutionConfig.TEPollution;
import ecomod.common.pollution.handlers.PollutionHandler;
import ecomod.common.proxy.ComProxy;

import java.util.ArrayList;
import java.util.Arrays;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import ecomod.api.pollution.PollutionData;
import ecomod.client.proxy.CliProxy;


@Mod(modid = EMConsts.modid, name = EMConsts.name, version = EMConsts.version, dependencies = EMConsts.deps, updateJSON = EMConsts.json, canBeDeactivated = false)
public class EcologyMod
{
	@Instance(EMConsts.modid)
	public static EcologyMod instance;
	
	public static Logger log;
	
	@SidedProxy(modId=EMConsts.modid, clientSide=EMConsts.client_proxy, serverSide=EMConsts.common_proxy)
	public static ComProxy proxy;
	
	public static PollutionHandler ph;
	
	public TEPollutionConfig tepc;
	
	//ModEventHandlers
	
	@EventHandler
	public void preInit(FMLPreInitializationEvent event)
	{
		log = LogManager.getLogger(EMConsts.name);
		
		log.info("Preinitialization");
		
		Configuration cfg = new Configuration(event.getSuggestedConfigurationFile());
		
		EMConfig.config = cfg;
		
		EMConfig.sync();
		
		setupMeta(event.getModMetadata());
		
		MainRegistry.doPreInit();
		
		ph = new PollutionHandler();
		
		MinecraftForge.EVENT_BUS.register(ph);
		
		tepc = new TEPollutionConfig();
		
		tepc.load(event.getModConfigurationDirectory().getAbsolutePath());
	}
	
	@EventHandler
	public void init(FMLInitializationEvent event)
	{
		log.info("Initialization");
		
		log.info(GameData.getTileEntityRegistry().getKeys().size());
		
		for(ResourceLocation rl : GameData.getTileEntityRegistry().getKeys())
		{
			log.info(rl.toString());
		}
	}
	
	@EventHandler
	public void postInit(FMLPostInitializationEvent event)
	{
		log.info("Postinitialization");
	}
	
	
	@EventHandler
	public void onIMC(IMCEvent event)
	{	
		for(IMCMessage m : event.getMessages())
		{
			if(m.key.toLowerCase().contentEquals("tepc_add") && m.isStringMessage())
			{
				TEPollution tep = TEPollution.fromJson(m.getStringValue());
				
				if(tep == null)
				{
					log.warn(m.getSender()+" tried to add TEPollution as "+m.getStringValue()+" but it has incorrect JSON syntax!");
				}
				else
				{
					if(tepc.hasTile(new ResourceLocation(tep.getId())))
					{
						log.warn("Mod ["+m.getSender()+"] replaced "+tepc.getTEP(tep.getId()).toString()+" in TEPC with "+tep.toString());
						tepc.data.remove(tepc.getTEP(tep.getId()));
					}
					else
					{
						log.info("Added "+tep.toString()+" to TEPC by "+m.getSender());
					}
					
					tepc.data.add(tep);
				}
			}
			
			if(m.key.toLowerCase().contentEquals("blacklist_item") && m.isStringMessage())
			{
				log.info("Mod ["+m.getSender()+"] blacklisted "+m.getStringValue());
				EMConfig.item_blacklist.add(m.getStringValue());
			}
		}
	}
	
	
	//Utils
	
	private static void setupMeta(ModMetadata meta)
	{
		meta.autogenerated=false;
		meta.credits = "Artem226";
		meta.authorList = Arrays.asList(new String[]{"Artem226"});
		meta.modId = EMConsts.modid;
		meta.name = EMConsts.name;
		meta.logoFile = "emlogo.png";
		meta.updateJSON = EMConsts.json;
		meta.url = EMConsts.projectURL;
		meta.version = EMConsts.version;
	}
}
